dogcollector/dogcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

dogcollector/main_app/urls.py
from django.urls import path
# From this file level, imports the views.py
from . import views

urlpatterns = [
    path('', views.home, name = 'home'),
    path('about/',views.about, name = 'about'),
    path('dogs/', views.dogs_index, name = 'dogs_index'),
    path('dogs/<int:dog_id>/', views.dog_details, name = 'details'),
    path('dogs/create/', views.DogCreate.as_view(), name='dogs_create'),
    path('dogs/<int:pk>/update', views.DogUpdate.as_view(), name='dog_update'),
    path('dogs/<int:pk>/delete', views.DogDelete.as_view(), name ='dog_delete'),
    path('dogs/<int:dog_id>/add_walk', views.add_walk, name='add_walk'),
    path('dogs/<int:dog_id>/assoc_friend/<int:friend_id>/', views.assoc_friend, name='assoc_friend'),
    # Friend Route
    path('friends/', views.FriendList.as_view(), name='friends_index'),
    path('friends/<int:pk>/', views.FriendDetail.as_view(), name='friends_detail'),
    path('friends/create/', views.FriendCreate.as_view(), name='friends_create'),
    path('friends/<int:pk>/update/', views.FriendUpdate.as_view(), name ='friends_update'),
    path('friends/<int:pk>/delete/', views.FriendDelete.as_view(), name ='friends_delete'),
    # Auth Routes
    path('accounts/signup/', views.signup, name='signup'),
]
# CBVs working w/ individual model instances expect to find a named parameter of pk. 
# This is why we didn't use cat_id as we did in the detail entry.

dogcollector/main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User

# Create your models here.

LOCATIONS = (
    ('P', 'Park'),
    ('N', 'Neighbourhood'),
    ('L', 'Lakeside')
)

class Friend(models.Model):
    name = models.CharField(max_length=50)
    breed = models.CharField(max_length=30)
    
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('friends_detail', kwargs={'pk': self.id})

class Dog(models.Model):
    name = models.CharField(max_length=100)
    breed = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    age = models.IntegerField()
    friends = models.ManyToManyField(Friend)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name
    
    # Returns page to detail page of created doggo
    def get_absolute_url(self):
        return reverse('details', kwargs={'dog_id': self.id})
    


# One to Many
class Walks(models.Model):
    date = models.DateField('Walk date')
    location = models.CharField(
        max_length=1,
        choices=LOCATIONS,
        default=LOCATIONS[0][0],
        )
    
    dog = models.ForeignKey(Dog, on_delete=models.CASCADE, null=True)
    
    def __str__(self):
        return f"{self.get_location_display()} on {self.date}"
    
    class Meta:
        ordering = ['-date']
    
    

dogcollector/main_app/forms.py
from django.forms import ModelForm
from .models import Walks

class WalksForm(ModelForm):
    class Meta:
        model = Walks
        fields = ['date', 'location']

dogcollector/main_app/views.py
from django.shortcuts import redirect, render
from .forms import WalksForm
from .models import Dog, Friend
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView

from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.


def home(request):
    return render(request, 'home.html')


def about(request):
    return render(request, 'about.html')


@login_required
def dogs_index(request):
    dogs = Dog.objects.all()
    return render(request, 'dogs/dogs_index.html', {'dogs': dogs})


@login_required
def dog_details(request, dog_id):
    dog = Dog.objects.get(id=dog_id)
    friends_dog_dont_have = Friend.objects.exclude(
        id__in=dog.friends.all().values_list('id'))
    walks_form = WalksForm()
    return render(request, 'dogs/detail.html', {
        'dog': dog,
        'walks_form': walks_form,
        'friends': friends_dog_dont_have
    })


class DogCreate(LoginRequiredMixin, CreateView):
    model = Dog
    # fields = '__all__' OR
    fields = ['name', 'breed', 'description', 'age']
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    # success_url = '/cats/' if absolute url method isnt used


class DogUpdate(LoginRequiredMixin, UpdateView):
    model = Dog
    fields = ['breed', 'description', 'age']


class DogDelete(LoginRequiredMixin, DeleteView):
    model = Dog
    success_url = '/dogs/'


@login_required
def add_walk(request, dog_id):
    form = WalksForm(request.POST)
    if form.is_valid():
        new_walk = form.save(commit=False)
        new_walk.dog_id = dog_id
        new_walk.save()
    return redirect('details', dog_id=dog_id)


def assoc_friend(request, dog_id, friend_id):
    Dog.objects.get(id=dog_id).friends.add(friend_id)
    return redirect('details', dog_id=dog_id)


def signup(request):
    error_message = ''
    if request.method == 'POST':
        # This is how to create a 'user' form object
        # that includes the data from the browser
        form = UserCreationForm(request.POST)
        if form.is_valid():
            # This will add the user to the database
            user = form.save()
        # This is how we log a user in via code
            login(request, user)
            return redirect('index')
        else:
            error_message = 'Invalid sign up - try again'
    # A bad POST or a GET request, so render signup.html with an empty form
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)


class FriendList(LoginRequiredMixin, ListView):
    model = Friend


class FriendDetail(LoginRequiredMixin, DetailView):
    model = Friend


class FriendCreate(LoginRequiredMixin, CreateView):
    model = Friend
    fields = '__all__'


class FriendUpdate(LoginRequiredMixin, UpdateView):
    model = Friend
    fields = ['name']


class FriendDelete(LoginRequiredMixin, DeleteView):
    model = Friend
    success_url = '/friends/'

dogcollector/main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}
<h1>About</h1>
{% endblock %}

dogcollector/main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Dog Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;Dog Collector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          {% if user.is_authenticated %}
            <li><a href="{% url 'friends_create' %}">Add a Friend</a></li>
            <li><a href="{% url 'friends_index' %}">View All Friends</a></li>
            <li><a href="{% url 'dogs_create' %}">Add a Doggo</a></li>
            <li><a href="{% url 'dogs_index' %}">All em Doggos</a></li>
            <li><a href="{% url 'logout' %}">Log Out</a></li>
          {% else %}
            <li><a href="{% url 'signup' %}">Sign Up</a></li>
            <li><a href="{% url 'login' %}">Log In</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">No Rights Reserved</div>
  </footer>
</body>
</html>

dogcollector/main_app/templates/dogs/detail.html
{% extends 'base.html' %} {% block content %}

<h1> Details</h1>

<div class="card col s5">
    <div class="card-content">
      <span class="card-title">{{dog.id}}:  {{ dog.name }}</span>
      <p>Breed: {{ dog.breed }}</p>
      <p>Description: {{ dog.description }}</p>
      <p>Age: {{ dog.age }}</p>
    </div>
    <div class="card-action">
      <a href="{% url 'dog_update' dog.id %}">Edit</a>
      <a href="{% url 'dog_delete' dog.id %}">Delete</a>
    </div>
</div>
<div class="col s5 card" >
  <form action='{% url 'add_walk' dog.id %}' method="post">
    {% csrf_token %}
    {{ walks_form.as_p }}
    <input type="submit" class="btn" value="Add Walk">
  </form>
  <table class="striped card-content">
    <thead>
      <tr><th>Date</th><th>Location</th></tr>
    </thead>
    <tbody>
      {% for walk in dog.walks_set.all %}
        <tr>
          <td>{{walk.date}}</td>
          <td>{{walk.get_location_display}}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
<hr>
<div class="row">
  <div class="col s6">
    <h3>{{ dog.name }}'s Friends</h3>
    {% if dog.friends.count %}
      {% for friend in dog.friends.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A {{ friend.breed }} named {{ friend.name }}
            </span>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No Friends :(</h5>
    {% endif %}
  </div>
  <!-- Available toys will come after this line -->
  <div class="col s6">
    <h3>Doggos you havent met</h3>
    {% if friends.count %}
      {% for friend in friends.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A {{ friend.breed }} named {{ friend.name }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_friend' dog.id friend.id %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>{{dog.name}} No new friends</h5>
    {% endif %}
  </div>
</div>
<script>
  var dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });

  let locationEl = document.getElementById('id_location')
  M.FormSelect.init(locationEl,{})
</script>
{% endblock %}

dogcollector/main_app/templates/dogs/dogs_index.html
{% extends 'base.html' %} {% block content %}

<h1>Their Doggos</h1>

{% for dog in dogs %}
<div class="card">
  <a href="{%url 'details' dog.id%}">
    <div class="card-content">
      <span class="card-title">{{ dog.name }}</span>
      <p>Breed: {{ dog.breed }}</p>
      <p>Description: {{ dog.description }}</p>
      <p>Age: {{ dog.age }}</p>
    </div>
  </a>
</div>
{% endfor %} {% endblock %}

dogcollector/main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}
<h1> Home</h1>
{% endblock %}

dogcollector/main_app/templates/main_app/dog_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Confirmation</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'details' dog.id %}">Cancel</a>
  </form>
{% endblock %}

dogcollector/main_app/templates/main_app/dog_form.html
{% extends 'base.html' %} 
{% block content %} 
{% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
    <h1>Add a Doggo</h1>
{% endif %}

<form action="" method="post">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit!" class="btn" />
</form>
{% endblock %}

dogcollector/main_app/templates/main_app/friend_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete DOGGO</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'friends_detail' friend.id %}">Cancel</a>
  </form>
{% endblock %}

dogcollector/main_app/templates/main_app/friend_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Friend Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ friend.name }}</span>
        <p>Breed: {{ friend.breed }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'friends_update' friend.id %}">Edit</a>
        <a href="{% url 'friends_delete' friend.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

dogcollector/main_app/templates/main_app/friend_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Friend</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

dogcollector/main_app/templates/main_app/friend_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Friend List</h1>

{% for friend in friend_list %}
  <a href="{% url 'friends_detail' friend.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ friend.name }}</span>
            <p>Breed: {{ friend.breed }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}